#!/usr/bin/env python3
"""
scripts/fetch_events.py
Automated Event Aggregator & Calendar Generator for DVERSE.
Aggregates and enriches 100 marquee Crypto, AI, and Decentralized AI (Crypto x AI) events.
Outputs statically to public/events.json.
"""

import json
import os
from datetime import datetime, date, timezone
from urllib.parse import quote

# 100 Premier Global Events Curated for 2026
CORE_EVENTS = [
    # -------------------------------------------------------------
    # 1. Crypto & Web3 Premier Summits (40 Events)
    # -------------------------------------------------------------
    {
        "id": "solana-breakpoint-2026",
        "title": "Solana Breakpoint 2026",
        "category": "Crypto",
        "badge": "Solana Flagship",
        "startDate": "2026-09-18",
        "endDate": "2026-09-20",
        "location": "Abu Dhabi, UAE",
        "venue": "ADNEC Center",
        "description": "The annual global gathering for the Solana ecosystem. Bringing together core developers, founders, decentralized AI pioneers, and institutional investors shaping high-throughput decentralized systems.",
        "topics": ["Solana", "DeAI & AI Agents", "High-Throughput DeFi", "Firedancer", "Infrastructure"],
        "officialUrl": "https://solana.com/breakpoint",
        "xHandle": "@SolanaBreakpoint",
        "isFeatured": True
    },
    {
        "id": "token2049-dubai-2026",
        "title": "TOKEN2049 Dubai",
        "category": "Crypto",
        "badge": "Flagship Summit",
        "startDate": "2026-04-29",
        "endDate": "2026-04-30",
        "location": "Dubai, UAE",
        "venue": "Madinat Jumeirah",
        "description": "The world's premier crypto conference where 15,000+ decision-makers, Web3 founders, crypto-AI protocols, and institutional capital converge for intensive networking and major product reveals.",
        "topics": ["Crypto x AI", "Web3 Infrastructure", "Institutional Adoption", "Tokenomics", "DeFi"],
        "officialUrl": "https://www.dubai.token2049.com",
        "xHandle": "@token2049",
        "isFeatured": True
    },
    {
        "id": "token2049-singapore-2026",
        "title": "TOKEN2049 Singapore",
        "category": "Crypto",
        "badge": "Flagship Summit",
        "startDate": "2026-10-07",
        "endDate": "2026-10-08",
        "location": "Singapore",
        "venue": "Marina Bay Sands",
        "description": "Asia's flagship crypto extravaganza running during Formula 1 race week. Attracts over 20,000 attendees, 500+ side events, and top venture capitalists from across the globe.",
        "topics": ["Venture Capital", "Asian Markets", "Crypto AI", "Scalability", "Ecosystem Funds"],
        "officialUrl": "https://www.asia.token2049.com",
        "xHandle": "@token2049",
        "isFeatured": True
    },
    {
        "id": "ethdenver-2026",
        "title": "ETHDenver 2026",
        "category": "Crypto",
        "badge": "Largest BUIDLathon",
        "startDate": "2026-02-17",
        "endDate": "2026-02-21",
        "location": "Denver, CO, USA",
        "venue": "National Western Complex",
        "description": "The largest and longest-running Web3 #BUIDLathon in the world. Thousands of open-source developers create smart contract protocols, autonomous agents, and cross-chain dApps.",
        "topics": ["Smart Contracts", "DeAI Hackathons", "Layer 2", "Public Goods", "Community Grants"],
        "officialUrl": "https://www.ethdenver.com",
        "xHandle": "@EthereumDenver",
        "isFeatured": False
    },
    {
        "id": "devcon-2026",
        "title": "Devcon 2026",
        "category": "Crypto",
        "badge": "Ethereum Flagship",
        "startDate": "2026-11-03",
        "endDate": "2026-11-06",
        "location": "Mumbai, India",
        "venue": "Jio World Convention Centre",
        "description": "The Ethereum Foundation's premier conference for developers, researchers, and community builders from all over the world, emphasizing decentralization and cryptographic proofs.",
        "topics": ["Ethereum", "Zero-Knowledge", "Layer 2 Rollups", "Cryptography", "Decentralized Governance"],
        "officialUrl": "https://devcon.org",
        "xHandle": "@EFDevcon",
        "isFeatured": False
    },
    {
        "id": "consensus-2026",
        "title": "Consensus 2026 by CoinDesk",
        "category": "Crypto",
        "badge": "Industry Benchmark",
        "startDate": "2026-05-13",
        "endDate": "2026-05-15",
        "location": "Toronto, Canada",
        "venue": "Metro Toronto Convention Centre",
        "description": "The world's largest, longest-running, and most influential gathering that brings together all sides of the cryptocurrency, blockchain, and Web3 ecosystem alongside global policymakers.",
        "topics": ["Institutional Web3", "DeFi", "Regulation & Policy", "Crypto Economy", "Crypto x AI"],
        "officialUrl": "https://consensus.coindesk.com",
        "xHandle": "@consensus2026",
        "isFeatured": False
    },
    {
        "id": "korea-blockchain-week-2026",
        "title": "Korea Blockchain Week (KBW 2026)",
        "category": "Crypto",
        "badge": "Asia Summit",
        "startDate": "2026-09-29",
        "endDate": "2026-10-01",
        "location": "Seoul, South Korea",
        "venue": "Walkerhill Hotels & Resorts",
        "description": "Founded by FactBlock and co-hosted by Hashed, KBW is the epicenter of Asian crypto innovation, gaming dApps, on-chain social experiences, and decentralized infrastructure.",
        "topics": ["Web3 Gaming", "Asian Liquidity", "Crypto Adoption", "Decentralized Social", "Layer 1s"],
        "officialUrl": "https://koreablockchainweek.com",
        "xHandle": "@kbwofficial",
        "isFeatured": False
    },
    {
        "id": "bitcoin-2026",
        "title": "Bitcoin 2026 Conference",
        "category": "Crypto",
        "badge": "Global Gathering",
        "startDate": "2026-04-27",
        "endDate": "2026-04-29",
        "location": "Las Vegas, NV, USA",
        "venue": "The Venetian Convention Expo",
        "description": "The largest celebration of Bitcoin in the world. Featuring sovereign nation mining updates, Lightning Network scale demonstrations, and sovereign open-source hardware.",
        "topics": ["Bitcoin", "Lightning Network", "Proof of Work Mining", "Sound Money", "Sovereign Tech"],
        "officialUrl": "https://b.tc/conference",
        "xHandle": "@TheBitcoinConf",
        "isFeatured": False
    },
    {
        "id": "paris-blockchain-week-2026",
        "title": "Paris Blockchain Week 2026",
        "category": "Crypto",
        "badge": "European Flagship",
        "startDate": "2026-04-08",
        "endDate": "2026-04-10",
        "location": "Paris, France",
        "venue": "Carrousel du Louvre",
        "description": "Europe's leading blockchain summit held inside the historic Louvre palace, bringing together enterprise leaders, protocol founders, and European regulatory authorities.",
        "topics": ["European Web3", "MiCA Regulations", "Institutional Crypto", "DeFi Protocols", "Web3 Luxury"],
        "officialUrl": "https://www.parisblockchainweek.com",
        "xHandle": "@ParisBlockWeek",
        "isFeatured": False
    },
    {
        "id": "ethcc-cannes-2026",
        "title": "EthCC [9] (Ethereum Community Conference)",
        "category": "Crypto",
        "badge": "European Flagship",
        "startDate": "2026-03-30",
        "endDate": "2026-04-02",
        "location": "Cannes, France",
        "venue": "Palais des Festivals et des Congrès",
        "description": "The largest annual European Ethereum event focused on technology and community. Over 250 presentations, workshops, and networking events for Web3 builders.",
        "topics": ["Ethereum", "Decentralized Governance", "Zero-Knowledge", "Layer 2", "Open Source"],
        "officialUrl": "https://ethcc.io",
        "xHandle": "@EthCC",
        "isFeatured": True
    },
    {
        "id": "permissionless-2026",
        "title": "Permissionless IV by Blockworks",
        "category": "Crypto",
        "badge": "DeFi & Modular Summit",
        "startDate": "2026-10-14",
        "endDate": "2026-10-16",
        "location": "Salt Lake City, UT, USA",
        "venue": "Salt Palace Convention Center",
        "description": "The cultural epicenter for crypto natives. Co-produced by Blockworks and Bankless, exploring modular blockchains, DeFi restaking, decentralized AI, and on-chain culture.",
        "topics": ["DeFi 2.0", "Restaking", "Modular Architecture", "Crypto Culture", "AI Agents"],
        "officialUrl": "https://blockworks.co/events/permissionless",
        "xHandle": "@Blockworks_",
        "isFeatured": True
    },
    {
        "id": "european-blockchain-convention-2026",
        "title": "European Blockchain Convention (EBC 2026)",
        "category": "Crypto",
        "badge": "European Summit",
        "startDate": "2026-10-22",
        "endDate": "2026-10-23",
        "location": "Barcelona, Spain",
        "venue": "Fira Barcelona Montjuïc",
        "description": "6,000+ attendees and 300+ speakers across 3 stages discussing digital assets, tokenization of real-world assets (RWA), institutional DeFi, and Web3 regulation.",
        "topics": ["RWA Tokenization", "Institutional Crypto", "DeFi", "Web3 Payments", "Fintech"],
        "officialUrl": "https://eblockchainconvention.com",
        "xHandle": "@EBlockchainConv",
        "isFeatured": False
    },
    {
        "id": "ethglobal-london-2026",
        "title": "ETHGlobal London 2026",
        "category": "Crypto",
        "badge": "Global Hackathon",
        "startDate": "2026-03-13",
        "endDate": "2026-03-15",
        "location": "London, UK",
        "venue": "Queen Elizabeth II Centre",
        "description": "A premier 36-hour weekend hackathon where top European developers build dApps, autonomous protocols, and account abstraction tools with leading mentors.",
        "topics": ["Hackathons", "Account Abstraction", "Smart Contracts", "DeFi", "L2"],
        "officialUrl": "https://ethglobal.com/events/london2026",
        "xHandle": "@ETHGlobal",
        "isFeatured": False
    },
    {
        "id": "ethglobal-tokyo-2026",
        "title": "ETHGlobal Tokyo 2026",
        "category": "Crypto",
        "badge": "Global Hackathon",
        "startDate": "2026-04-17",
        "endDate": "2026-04-19",
        "location": "Tokyo, Japan",
        "venue": "Toranomon Hills Forum",
        "description": "Uniting Asia's sharpest developers with global protocol architects. Hackers compete for bounties in decentralized identity, AI agents, and scaling solutions.",
        "topics": ["Hackathon", "Asia Developers", "Smart Contracts", "Web3 Gaming", "zkEVM"],
        "officialUrl": "https://ethglobal.com/events/tokyo2026",
        "xHandle": "@ETHGlobal",
        "isFeatured": False
    },
    {
        "id": "ethglobal-sf-2026",
        "title": "ETHGlobal San Francisco 2026",
        "category": "Crypto",
        "badge": "Silicon Valley Hackathon",
        "startDate": "2026-10-16",
        "endDate": "2026-10-18",
        "location": "San Francisco, CA, USA",
        "venue": "Palace of Fine Arts",
        "description": "The flagship hackathon of Silicon Valley where AI founders and Web3 engineers join forces to build autonomous decentralized applications and agent networks.",
        "topics": ["Crypto x AI", "Agentic Systems", "Silicon Valley Web3", "Hackathon", "DePIN"],
        "officialUrl": "https://ethglobal.com/events/sanfrancisco2026",
        "xHandle": "@ETHGlobal",
        "isFeatured": True
    },
    {
        "id": "ethglobal-singapore-2026",
        "title": "ETHGlobal Singapore 2026",
        "category": "Crypto",
        "badge": "Global Hackathon",
        "startDate": "2026-09-25",
        "endDate": "2026-09-27",
        "location": "Singapore",
        "venue": "Suntec Singapore Convention Centre",
        "description": "Connecting Southeast Asian talent with global sponsors. Hundreds of teams build cutting-edge decentralized applications with round-the-clock mentorship.",
        "topics": ["Hackathons", "DeFi", "Layer 2", "Public Goods", "Community Grants"],
        "officialUrl": "https://ethglobal.com/events/singapore2026",
        "xHandle": "@ETHGlobal",
        "isFeatured": False
    },
    {
        "id": "ethglobal-brussels-2026",
        "title": "ETHGlobal Brussels 2026",
        "category": "Crypto",
        "badge": "Global Hackathon",
        "startDate": "2026-07-10",
        "endDate": "2026-07-12",
        "location": "Brussels, Belgium",
        "venue": "The EGG Brussels",
        "description": "Gathering European developers for a high-intensity hackathon right in the administrative capital of Europe.",
        "topics": ["Hackathon", "Zero-Knowledge", "Governance", "Privacy", "DeFi"],
        "officialUrl": "https://ethglobal.com",
        "xHandle": "@ETHGlobal",
        "isFeatured": False
    },
    {
        "id": "consensus-hong-kong-2026",
        "title": "Consensus Hong Kong 2026",
        "category": "Crypto",
        "badge": "Asia Flagship",
        "startDate": "2026-02-10",
        "endDate": "2026-02-12",
        "location": "Hong Kong",
        "venue": "Hong Kong Convention and Exhibition Centre",
        "description": "Bringing the iconic CoinDesk Consensus brand to Asia, exploring institutional crypto flows, stablecoin frameworks, and Chinese Web3 market expansion.",
        "topics": ["Asian Crypto", "Stablecoins", "Regulation", "Institutional Capital", "Trading"],
        "officialUrl": "https://consensus-hongkong.coindesk.com",
        "xHandle": "@consensus2026",
        "isFeatured": False
    },
    {
        "id": "bitcoin-asia-2026",
        "title": "Bitcoin Asia 2026",
        "category": "Crypto",
        "badge": "Regional Summit",
        "startDate": "2026-05-08",
        "endDate": "2026-05-09",
        "location": "Hong Kong",
        "venue": "Kai Tak Cruise Terminal",
        "description": "Asia's premier Bitcoin conference focusing on Ordinals, Runes, Layer 2 scaling, sovereign custody, and institutional Bitcoin treasury allocations.",
        "topics": ["Bitcoin", "Ordinals", "Runes", "Lightning", "Institutional BTC"],
        "officialUrl": "https://b.tc/conference/asia",
        "xHandle": "@TheBitcoinConf",
        "isFeatured": False
    },
    {
        "id": "zk-summit-13-2026",
        "title": "ZK Summit 13 (Zero-Knowledge Summit)",
        "category": "Crypto",
        "badge": "Cryptography Research",
        "startDate": "2026-04-14",
        "endDate": "2026-04-14",
        "location": "Berlin, Germany",
        "venue": "Kühlhaus Berlin",
        "description": "The leading technical symposium for zero-knowledge proofs, recursive SNARKs, STARK architectures, and verifiable computing researchers.",
        "topics": ["Zero-Knowledge", "SNARKs", "STARKs", "zkML", "Verifiable Compute"],
        "officialUrl": "https://www.zksummit.com",
        "xHandle": "@zeroknowledgefm",
        "isFeatured": True
    },
    {
        "id": "zk-summit-14-2026",
        "title": "ZK Summit 14 (Zero-Knowledge Summit)",
        "category": "Crypto",
        "badge": "Cryptography Research",
        "startDate": "2026-10-20",
        "endDate": "2026-10-20",
        "location": "Athens, Greece",
        "venue": "Megaron Athens International Conference Centre",
        "description": "Focusing on the latest cryptographic breakthroughs, polynomial commitments, folding schemes, and hardware acceleration for ZK proofs.",
        "topics": ["Cryptography", "Hardware Acceleration", "zkEVM", "zkRollups", "Verifiable AI"],
        "officialUrl": "https://www.zksummit.com",
        "xHandle": "@zeroknowledgefm",
        "isFeatured": False
    },
    {
        "id": "sui-basecamp-2026",
        "title": "Sui Basecamp 2026",
        "category": "Crypto",
        "badge": "Ecosystem Summit",
        "startDate": "2026-04-22",
        "endDate": "2026-04-23",
        "location": "Dubai, UAE",
        "venue": "Jumeirah Beach Hotel",
        "description": "Mysten Labs' annual conference for builders, developers, and investors in the Sui Move ecosystem, highlighting object-centric blockchain design.",
        "topics": ["Sui", "Move Language", "Web3 Gaming", "High Throughput", "DeFi"],
        "officialUrl": "https://sui.io/basecamp",
        "xHandle": "@SuiNetwork",
        "isFeatured": False
    },
    {
        "id": "avalanche-summit-2026",
        "title": "Avalanche Summit LATAM 2026",
        "category": "Crypto",
        "badge": "Ecosystem Summit",
        "startDate": "2026-10-14",
        "endDate": "2026-10-16",
        "location": "Buenos Aires, Argentina",
        "venue": "Ciudad Cultural Konex",
        "description": "Bringing together researchers, developers, and institutions to explore Avalanche Subnets, interoperability, enterprise asset tokenization, and consumer Web3.",
        "topics": ["Avalanche", "Subnets", "Interoperability", "RWA", "Latin America Web3"],
        "officialUrl": "https://www.avax.network",
        "xHandle": "@AvalancheAVAX",
        "isFeatured": False
    },
    {
        "id": "cosmoverse-2026",
        "title": "Cosmoverse 2026",
        "category": "Crypto",
        "badge": "Interchain Summit",
        "startDate": "2026-10-26",
        "endDate": "2026-10-28",
        "location": "Dubai, UAE",
        "venue": "Grand Hyatt Dubai",
        "description": "The premier conference for the Cosmos and Interchain ecosystem. Covering IBC protocol expansions, modular rollups, shared security, and appchains.",
        "topics": ["Cosmos", "IBC", "Appchains", "Shared Security", "Modular Rollups"],
        "officialUrl": "https://cosmoverse.org",
        "xHandle": "@CosmoverseHQ",
        "isFeatured": False
    },
    {
        "id": "web3-summit-berlin-2026",
        "title": "Web3 Summit Berlin 2026",
        "category": "Crypto",
        "badge": "Decentralization Forum",
        "startDate": "2026-08-18",
        "endDate": "2026-08-20",
        "location": "Berlin, Germany",
        "venue": "Funkhaus Berlin",
        "description": "Organized by the Web3 Foundation. A technical, non-commercial gathering of cypherpunks, protocol architects, and privacy researchers advocating for user sovereignty.",
        "topics": ["Cypherpunk", "Privacy", "Peer-to-Peer", "Decentralized Storage", "Cryptography"],
        "officialUrl": "https://web3summit.com",
        "xHandle": "@web3foundation",
        "isFeatured": True
    },
    {
        "id": "devconnect-2026",
        "title": "Devconnect 2026",
        "category": "Crypto",
        "badge": "Intensive Co-working",
        "startDate": "2026-11-15",
        "endDate": "2026-11-21",
        "location": "Amsterdam, Netherlands",
        "venue": "Beurs van Berlage",
        "description": "A week-long series of independent, collaborative Ethereum workshops and deep dives focusing on specific research topics like MEV, staking, and data availability.",
        "topics": ["MEV", "Data Availability", "Ethereum Research", "Staking", "Co-working"],
        "officialUrl": "https://devconnect.org",
        "xHandle": "@EFDevconnect",
        "isFeatured": False
    },
    {
        "id": "solana-hacker-house-berlin-2026",
        "title": "Solana Hacker House Berlin",
        "category": "Crypto",
        "badge": "Solana Builders",
        "startDate": "2026-05-18",
        "endDate": "2026-05-22",
        "location": "Berlin, Germany",
        "venue": "Station Berlin",
        "description": "A five-day co-working, building, and mentorship event dedicated to Solana ecosystem engineers with direct support from Solana Foundation core developers.",
        "topics": ["Solana", "Rust", "Anchor", "High-Speed dApps", "Hackathon"],
        "officialUrl": "https://solana.com/community/hacker-houses",
        "xHandle": "@Solana",
        "isFeatured": False
    },
    {
        "id": "solana-hacker-house-bangalore-2026",
        "title": "Solana Hacker House Bangalore",
        "category": "Crypto",
        "badge": "Solana Builders",
        "startDate": "2026-06-22",
        "endDate": "2026-06-26",
        "location": "Bangalore, India",
        "venue": "The Leela Palace Bangalore",
        "description": "Gathering India's developer powerhouse for a 5-day deep dive into Solana protocol engineering, micro-payments, and autonomous agent systems.",
        "topics": ["Solana", "India Builders", "DeFi", "AI Micro-Payments", "Superteam"],
        "officialUrl": "https://solana.com/community/hacker-houses",
        "xHandle": "@SuperteamIN",
        "isFeatured": True
    },
    {
        "id": "solana-hacker-house-nyc-2026",
        "title": "Solana Hacker House New York",
        "category": "Crypto",
        "badge": "Solana Builders",
        "startDate": "2026-08-03",
        "endDate": "2026-08-07",
        "location": "New York, NY, USA",
        "venue": "Spring Studios Manhattan",
        "description": "Connecting Wall Street liquidity with high-performance Solana engineering. Workshops on institutional order books, perpetuals, and DePIN networks.",
        "topics": ["Solana", "Institutional DeFi", "Order Books", "DePIN", "Fintech"],
        "officialUrl": "https://solana.com/community/hacker-houses",
        "xHandle": "@Solana",
        "isFeatured": False
    },
    {
        "id": "solana-hacker-house-tokyo-2026",
        "title": "Solana Hacker House Tokyo",
        "category": "Crypto",
        "badge": "Solana Builders",
        "startDate": "2026-09-07",
        "endDate": "2026-09-11",
        "location": "Tokyo, Japan",
        "venue": "Shibuya Stream Hall",
        "description": "Exploring high-speed gaming infrastructure, on-chain IP, and decentralized autonomous intelligence built on Solana.",
        "topics": ["Solana", "Gaming", "Digital Assets", "Asia Ecosystem", "Rust"],
        "officialUrl": "https://solana.com/community/hacker-houses",
        "xHandle": "@SuperteamJapan",
        "isFeatured": False
    },
    {
        "id": "chainlink-smartcon-2026",
        "title": "Chainlink SmartCon 2026",
        "category": "Crypto",
        "badge": "Oracle & Interop Summit",
        "startDate": "2026-10-28",
        "endDate": "2026-10-29",
        "location": "New York, NY, USA",
        "venue": "Javits Center",
        "description": "Where Web3 converges with traditional finance. Showcasing Cross-Chain Interoperability Protocol (CCIP), decentralized oracles, and real-world asset proofs.",
        "topics": ["Chainlink", "CCIP", "Oracles", "TradFi Integration", "Tokenized Assets"],
        "officialUrl": "https://smartcon.chain.link",
        "xHandle": "@chainlink",
        "isFeatured": False
    },
    {
        "id": "nearcon-2026",
        "title": "NEARcon 2026",
        "category": "Crypto",
        "badge": "Chain Abstraction",
        "startDate": "2026-11-09",
        "endDate": "2026-11-11",
        "location": "Lisbon, Portugal",
        "venue": "Convento do Beato",
        "description": "NEAR Foundation's flagship ecosystem conference focusing on chain abstraction, user-owned AI models, and fast decentralized data availability.",
        "topics": ["NEAR", "Chain Abstraction", "User-Owned AI", "Sharding", "Data Availability"],
        "officialUrl": "https://nearcon.org",
        "xHandle": "@NEARProtocol",
        "isFeatured": False
    },
    {
        "id": "polkadot-decoded-2026",
        "title": "Polkadot Decoded 2026",
        "category": "Crypto",
        "badge": "Ecosystem Summit",
        "startDate": "2026-07-01",
        "endDate": "2026-07-02",
        "location": "Brussels, Belgium",
        "venue": "Square Brussels Convention Centre",
        "description": "The premier event for the Polkadot ecosystem showcasing JAM (Join-Accumulate Machine), agile coretime, and decentralized asynchronous backing.",
        "topics": ["Polkadot", "Substrate", "JAM", "Interoperability", "Coretime"],
        "officialUrl": "https://decoded.polkadot.network",
        "xHandle": "@Polkadot",
        "isFeatured": False
    },
    {
        "id": "dappcon-berlin-2026",
        "title": "DappCon Berlin 2026",
        "category": "Crypto",
        "badge": "Ethereum Infrastructure",
        "startDate": "2026-05-19",
        "endDate": "2026-05-21",
        "location": "Berlin, Germany",
        "venue": "Radialsystem V",
        "description": "Hosted by Gnosis. A developer conference for Ethereum infrastructure and dApp engineering, discussing smart contracts, account abstraction, and decentralized governance.",
        "topics": ["Gnosis", "Smart Contracts", "dApps", "Account Abstraction", "Infra"],
        "officialUrl": "https://dappcon.io",
        "xHandle": "@dappcon_berlin",
        "isFeatured": False
    },
    {
        "id": "web3-berlin-2026",
        "title": "Web3 Berlin 2026",
        "category": "Crypto",
        "badge": "General Web3",
        "startDate": "2026-06-11",
        "endDate": "2026-06-12",
        "location": "Berlin, Germany",
        "venue": "Estrel Congress Center",
        "description": "One of Europe's largest grassroots crypto gatherings uniting founders, developers, NFT communities, and DeFi creators.",
        "topics": ["Web3", "NFTs", "DeFi", "Community", "Crypto Culture"],
        "officialUrl": "https://berlinweb3.com",
        "xHandle": "@web3berlin",
        "isFeatured": False
    },
    {
        "id": "istanbul-blockchain-week-2026",
        "title": "Istanbul Blockchain Week 2026",
        "category": "Crypto",
        "badge": "Regional Hub",
        "startDate": "2026-08-11",
        "endDate": "2026-08-13",
        "location": "Istanbul, Turkey",
        "venue": "Hilton Istanbul Bomonti",
        "description": "Connecting Eurasian blockchain markets, Turkish crypto traders, and global Web3 protocol teams at the crossroads of Europe and Asia.",
        "topics": ["Eurasia Web3", "Trading", "Exchange Liquidity", "DeFi", "Adoption"],
        "officialUrl": "https://istanbulblockchainweek.com",
        "xHandle": "@IBlockchainWeek",
        "isFeatured": False
    },
    {
        "id": "japan-blockchain-week-2026",
        "title": "Japan Blockchain Week 2026",
        "category": "Crypto",
        "badge": "Asia Summit",
        "startDate": "2026-07-06",
        "endDate": "2026-07-12",
        "location": "Tokyo, Japan",
        "venue": "Various Venues Across Tokyo",
        "description": "A nationwide celebration of blockchain and gaming technology backed by Japanese enterprises, Web3 incubators, and government initiatives.",
        "topics": ["Japan Web3", "Gaming", "Enterprise Blockchain", "IP Rights", "Anime"],
        "officialUrl": "https://japanblockchainweek.jp",
        "xHandle": "@JBlockchainWeek",
        "isFeatured": False
    },
    {
        "id": "blockchain-life-dubai-2026",
        "title": "Blockchain Life Dubai 2026",
        "category": "Crypto",
        "badge": "Global Forum",
        "startDate": "2026-10-21",
        "endDate": "2026-10-22",
        "location": "Dubai, UAE",
        "venue": "Festival Arena Dubai",
        "description": "10,000+ international attendees from 120 countries discussing crypto mining, global market trends, venture capital, and token launches.",
        "topics": ["Mining", "Venture Capital", "Token Launches", "Trading", "DeFi"],
        "officialUrl": "https://blockchain-life.com",
        "xHandle": "@Blife_Forum",
        "isFeatured": False
    },
    {
        "id": "aus-crypto-convention-2026",
        "title": "Australian Crypto Convention 2026",
        "category": "Crypto",
        "badge": "Southern Hemisphere Flagship",
        "startDate": "2026-11-21",
        "endDate": "2026-11-22",
        "location": "Sydney, Australia",
        "venue": "International Convention Centre (ICC) Sydney",
        "description": "The largest cryptocurrency and digital asset conference in the Southern Hemisphere, bringing together 12,000+ investors and builders.",
        "topics": ["Australian Web3", "Regulation", "DeFi", "Institutional Custody", "Fintech"],
        "officialUrl": "https://auscryptocon.com",
        "xHandle": "@AusCryptoCon",
        "isFeatured": False
    },
    {
        "id": "solana-hacker-house-singapore-2026",
        "title": "Solana Hacker House Singapore",
        "category": "Crypto",
        "badge": "Solana Builders",
        "startDate": "2026-10-02",
        "endDate": "2026-10-06",
        "location": "Singapore",
        "venue": "Marina Bay Convention Hall",
        "description": "Co-located during Token2049 week. Builders compete in rapid hack sprints building decentralized AI, payment streams, and Solana DeFi dApps.",
        "topics": ["Solana", "Token2049 Week", "Superteam", "AI Payments", "Hackathon"],
        "officialUrl": "https://solana.com/community/hacker-houses",
        "xHandle": "@Solana",
        "isFeatured": True
    },

    # -------------------------------------------------------------
    # 2. Artificial Intelligence & Frontier ML (40 Events)
    # -------------------------------------------------------------
    {
        "id": "nvidia-gtc-2026",
        "title": "NVIDIA GTC 2026",
        "category": "AI",
        "badge": "Frontier AI Flagship",
        "startDate": "2026-03-16",
        "endDate": "2026-03-19",
        "location": "San Jose, CA, USA",
        "venue": "San Jose McEnery Convention Center",
        "description": "The global developer conference for the era of AI. Jensen Huang delivers the keynote covering next-gen Blackwell/Rubin GPU architectures, physical AI, foundational LLM models, and accelerated computing.",
        "topics": ["GPU Compute", "Foundational Models", "Robotics", "Autonomous Systems", "Enterprise AI"],
        "officialUrl": "https://www.nvidia.com/gtc/",
        "xHandle": "@NVIDIAGTC",
        "isFeatured": True
    },
    {
        "id": "openai-devday-2026",
        "title": "OpenAI DevDay 2026",
        "category": "AI",
        "badge": "Developer Flagship",
        "startDate": "2026-11-05",
        "endDate": "2026-11-06",
        "location": "San Francisco, CA, USA",
        "venue": "San Francisco & Global Livestream",
        "description": "OpenAI's annual conference for software engineers and machine learning builders. Showcasing next-generation frontier models, advanced agentic frameworks, and developer APIs.",
        "topics": ["Reasoning Models", "Agentic Systems", "Realtime API", "Fine-Tuning", "Synthetic Data"],
        "officialUrl": "https://devday.openai.com",
        "xHandle": "@OpenAI",
        "isFeatured": True
    },
    {
        "id": "google-io-2026",
        "title": "Google I/O 2026",
        "category": "AI",
        "badge": "Frontier AI & Cloud",
        "startDate": "2026-05-19",
        "endDate": "2026-05-20",
        "location": "Mountain View, CA, USA",
        "venue": "Shoreline Amphitheatre",
        "description": "Google's flagship annual developer festival highlighting major advancements across the Gemini model family, Vertex AI, autonomous coding agents, and mobile ecosystem innovations.",
        "topics": ["Gemini AI", "TPU Infrastructure", "Android AI", "Web Ecosystem", "Developer Tools"],
        "officialUrl": "https://io.google",
        "xHandle": "@googledevs",
        "isFeatured": False
    },
    {
        "id": "neurips-2026",
        "title": "NeurIPS 2026 (Conference on Neural Information Processing)",
        "category": "AI",
        "badge": "Top Research Summit",
        "startDate": "2026-12-07",
        "endDate": "2026-12-13",
        "location": "Vancouver, BC, Canada",
        "venue": "Vancouver Convention Centre",
        "description": "The highest-impact academic research conference in artificial intelligence, neural architectures, deep learning, cognitive neuroscience, and theoretical machine learning.",
        "topics": ["Deep Learning", "Reinforcement Learning", "AI Safety", "Mathematical Foundations", "Transformers"],
        "officialUrl": "https://neurips.cc",
        "xHandle": "@NeuripsConf",
        "isFeatured": True
    },
    {
        "id": "icml-2026",
        "title": "ICML 2026 (International Conference on Machine Learning)",
        "category": "AI",
        "badge": "Top Research Summit",
        "startDate": "2026-07-12",
        "endDate": "2026-07-18",
        "location": "Vienna, Austria",
        "venue": "Messe Wien Exhibition & Congress Center",
        "description": "One of the two most prestigious international machine learning conferences in computer science. Unveils breakthrough papers on generative algorithms, optimization, and scalable learning.",
        "topics": ["Machine Learning Theory", "Generative Modeling", "Explainable AI", "Large Models", "Algorithms"],
        "officialUrl": "https://icml.cc",
        "xHandle": "@icmlconf",
        "isFeatured": False
    },
    {
        "id": "cvpr-2026",
        "title": "CVPR 2026 (Computer Vision and Pattern Recognition)",
        "category": "AI",
        "badge": "Vision AI Flagship",
        "startDate": "2026-06-15",
        "endDate": "2026-06-19",
        "location": "Seattle, WA, USA",
        "venue": "Seattle Convention Center",
        "description": "The premier annual computer vision event comprising the main conference and workshops focusing on multimodal vision-language models, diffusion, 3D generation, and spatial AI.",
        "topics": ["Computer Vision", "Multimodal AI", "Diffusion Models", "Spatial Computing", "Autonomous Driving"],
        "officialUrl": "https://cvpr.thecvf.com",
        "xHandle": "@CVPR",
        "isFeatured": False
    },
    {
        "id": "iclr-2026",
        "title": "ICLR 2026 (International Conference on Learning Representations)",
        "category": "AI",
        "badge": "Deep Learning Flagship",
        "startDate": "2026-04-26",
        "endDate": "2026-04-30",
        "location": "Singapore",
        "venue": "Suntec Singapore Convention Centre",
        "description": "Globally recognized for presenting cutting-edge research on representation learning across deep learning, self-supervised learning, and neural network interpretability.",
        "topics": ["Representation Learning", "Self-Supervised", "Neural Architecture", "LLM Fine-Tuning", "Optimization"],
        "officialUrl": "https://iclr.cc",
        "xHandle": "@iclr_conf",
        "isFeatured": True
    },
    {
        "id": "aaai-2026",
        "title": "AAAI 2026 Conference on Artificial Intelligence",
        "category": "AI",
        "badge": "AI Foundations",
        "startDate": "2026-02-24",
        "endDate": "2026-03-02",
        "location": "Philadelphia, PA, USA",
        "venue": "Pennsylvania Convention Center",
        "description": "The 40th AAAI Conference promotes research in artificial intelligence and scientific exchange among AI researchers, practitioners, scientists, and engineers in affiliated disciplines.",
        "topics": ["Knowledge Representation", "Planning", "Automated Reasoning", "AI Ethics", "Robotics"],
        "officialUrl": "https://aaai.org/conference/aaai/aaai-26/",
        "xHandle": "@RealAAAI",
        "isFeatured": False
    },
    {
        "id": "ijcai-2026",
        "title": "IJCAI 2026 (International Joint Conference on AI)",
        "category": "AI",
        "badge": "Global Research",
        "startDate": "2026-08-15",
        "endDate": "2026-08-21",
        "location": "Bremen, Germany",
        "venue": "Congress Centrum Bremen",
        "description": "The oldest and one of the most prestigious AI conferences in the world, bringing together researchers across machine learning, multi-agent systems, and cognitive robotics.",
        "topics": ["Multi-Agent Systems", "Cognitive Robotics", "Machine Learning", "Game Theory", "NLP"],
        "officialUrl": "https://www.ijcai.org",
        "xHandle": "@IJCAIconf",
        "isFeatured": False
    },
    {
        "id": "acl-2026",
        "title": "ACL 2026 (Association for Computational Linguistics)",
        "category": "AI",
        "badge": "NLP & Language AI",
        "startDate": "2026-08-02",
        "endDate": "2026-08-07",
        "location": "Bangkok, Thailand",
        "venue": "Queen Sirikit National Convention Center",
        "description": "The flagship conference of the Association for Computational Linguistics. The definitive gathering for researchers developing large language models and natural language understanding.",
        "topics": ["Natural Language Processing", "LLM Architectures", "Machine Translation", "Semantics", "Speech"],
        "officialUrl": "https://www.aclweb.org",
        "xHandle": "@aclmeeting",
        "isFeatured": False
    },
    {
        "id": "kdd-2026",
        "title": "SIGKDD 2026 (Knowledge Discovery and Data Mining)",
        "category": "AI",
        "badge": "Data Science & AI",
        "startDate": "2026-08-09",
        "endDate": "2026-08-13",
        "location": "San Diego, CA, USA",
        "venue": "San Diego Convention Center",
        "description": "The premier interdisciplinary conference bringing together researchers and practitioners from data science, big data analytics, deep graph learning, and predictive modeling.",
        "topics": ["Data Mining", "Graph Neural Networks", "Big Data", "Recommender Systems", "Predictive Analytics"],
        "officialUrl": "https://kdd.org/kdd2026",
        "xHandle": "@kdd_news",
        "isFeatured": False
    },
    {
        "id": "siggraph-2026",
        "title": "ACM SIGGRAPH 2026",
        "category": "AI",
        "badge": "Graphics & Generative 3D",
        "startDate": "2026-08-09",
        "endDate": "2026-08-13",
        "location": "Los Angeles, CA, USA",
        "venue": "Los Angeles Convention Center",
        "description": "The world's leading annual conference on computer graphics and interactive techniques, unveiling breakthroughs in neural rendering, Gaussian splatting, and generative 3D physics.",
        "topics": ["Neural Rendering", "Generative 3D", "Gaussian Splatting", "Computer Graphics", "VR/AR"],
        "officialUrl": "https://s2026.siggraph.org",
        "xHandle": "@siggraph",
        "isFeatured": True
    },
    {
        "id": "aws-reinvent-2026",
        "title": "AWS re:Invent 2026",
        "category": "AI",
        "badge": "Cloud AI Flagship",
        "startDate": "2026-11-30",
        "endDate": "2026-12-04",
        "location": "Las Vegas, NV, USA",
        "venue": "Venetian, Mandalay Bay & Caesars Forum",
        "description": "Amazon Web Services' marquee learning conference for the global cloud and AI computing community, featuring major product launches across Bedrock, custom Trainium chips, and serverless architectures.",
        "topics": ["Cloud AI", "Custom Silicon", "Amazon Bedrock", "Data Centers", "Enterprise Compute"],
        "officialUrl": "https://reinvent.awsevents.com",
        "xHandle": "@AWSreInvent",
        "isFeatured": False
    },
    {
        "id": "microsoft-build-2026",
        "title": "Microsoft Build 2026",
        "category": "AI",
        "badge": "Enterprise Developer Day",
        "startDate": "2026-05-19",
        "endDate": "2026-05-21",
        "location": "Seattle, WA, USA",
        "venue": "Seattle Convention Center",
        "description": "Microsoft's annual conference for developers and engineers, showcasing Azure AI, Copilot Studio expansions, open-source model fine-tuning, and Windows on ARM.",
        "topics": ["Azure AI", "Copilot Studio", "LLM Fine-Tuning", "Cloud Infrastructure", "DevTools"],
        "officialUrl": "https://build.microsoft.com",
        "xHandle": "@OpenAtMicrosoft",
        "isFeatured": False
    },
    {
        "id": "meta-connect-2026",
        "title": "Meta Connect 2026",
        "category": "AI",
        "badge": "Open Source AI & XR",
        "startDate": "2026-09-23",
        "endDate": "2026-09-24",
        "location": "Menlo Park, CA, USA",
        "venue": "Meta HQ Menlo Park & Livestream",
        "description": "Mark Zuckerberg's keynote unveiling the next iteration of open-source Llama foundational weights, multimodal smart glasses, and spatial computing operating systems.",
        "topics": ["Llama Open Weights", "Smart Glasses", "Spatial AI", "Meta Quest", "Multimodal Models"],
        "officialUrl": "https://www.metaconnect.com",
        "xHandle": "@Meta",
        "isFeatured": True
    },
    {
        "id": "ai-summit-london-2026",
        "title": "The AI Summit London 2026",
        "category": "AI",
        "badge": "Enterprise AI",
        "startDate": "2026-06-10",
        "endDate": "2026-06-11",
        "location": "London, UK",
        "venue": "Tobacco Dock London",
        "description": "The flagship commercial AI summit analyzing tangible enterprise deployment of neural technologies, ethical governance, and next-generation developer tooling across Europe.",
        "topics": ["Enterprise AI", "AI Ethics & Safety", "Generative Workflow", "FinTech AI", "Regulatory Policy"],
        "officialUrl": "https://london.theaisummit.com",
        "xHandle": "@TheAISummit",
        "isFeatured": False
    },
    {
        "id": "ai-summit-ny-2026",
        "title": "The AI Summit New York 2026",
        "category": "AI",
        "badge": "Enterprise AI",
        "startDate": "2026-12-09",
        "endDate": "2026-12-10",
        "location": "New York, NY, USA",
        "venue": "Javits Center",
        "description": "Bringing together Fortune 500 decision-makers and AI start-up founders to discuss the ROI of generative AI implementations across finance, healthcare, and retail.",
        "topics": ["Enterprise AI", "Wall Street AI", "Healthcare Tech", "ROI of AI", "Governance"],
        "officialUrl": "https://newyork.theaisummit.com",
        "xHandle": "@TheAISummit",
        "isFeatured": False
    },
    {
        "id": "ai-engineer-worlds-fair-2026",
        "title": "AI Engineer World's Fair 2026",
        "category": "AI",
        "badge": "AI Engineering Premier",
        "startDate": "2026-06-24",
        "endDate": "2026-06-26",
        "location": "San Francisco, CA, USA",
        "venue": "Fort Mason Center",
        "description": "The premier conference for the emerging discipline of AI Engineering. 4,000+ software developers building compound AI systems, autonomous agents, and RAG pipelines.",
        "topics": ["AI Engineering", "Autonomous Agents", "RAG Pipelines", "Evaluations", "Prompt Engineering"],
        "officialUrl": "https://www.ai.engineer/worlds-fair",
        "xHandle": "@aiagentsummit",
        "isFeatured": True
    },
    {
        "id": "ai-engineer-summit-2026",
        "title": "AI Engineer Summit 2026",
        "category": "AI",
        "badge": "AI Engineering",
        "startDate": "2026-10-08",
        "endDate": "2026-10-09",
        "location": "San Francisco, CA, USA",
        "venue": "The Regency Ballroom",
        "description": "Technical deep dives on agentic architecture, LLM evals, DSPy prompt optimization, local model fine-tuning, and open-source inference stacks.",
        "topics": ["Agentic Stacks", "LLM Evals", "Local Models", "DSPy", "Inference Optimization"],
        "officialUrl": "https://www.ai.engineer",
        "xHandle": "@aiagentsummit",
        "isFeatured": False
    },
    {
        "id": "world-ai-cannes-festival-2026",
        "title": "World AI Cannes Festival (WAICF 2026)",
        "category": "AI",
        "badge": "Global Summit",
        "startDate": "2026-02-12",
        "endDate": "2026-02-14",
        "location": "Cannes, France",
        "venue": "Palais des Festivals et des Congrès",
        "description": "A prestigious global event bringing together 15,000+ attendees to explore AI's impact on society, enterprise digital transformation, and sovereign European AI initiatives.",
        "topics": ["European AI", "Sovereign AI", "Society & Ethics", "Enterprise Innovation", "Startups"],
        "officialUrl": "https://www.worldaicannes.com",
        "xHandle": "@WorldAICannes",
        "isFeatured": False
    },
    {
        "id": "ai-hardware-summit-2026",
        "title": "AI Hardware & Edge AI Summit 2026",
        "category": "AI",
        "badge": "Semiconductors & Compute",
        "startDate": "2026-09-08",
        "endDate": "2026-09-10",
        "location": "Santa Clara, CA, USA",
        "venue": "Santa Clara Convention Center",
        "description": "The definitive semiconductor conference analyzing AI chips, custom silicon, high-bandwidth memory (HBM), and optical interconnects for massive scale training clusters.",
        "topics": ["AI Silicon", "Custom ASICs", "HBM Memory", "Edge AI", "Data Center Cooling"],
        "officialUrl": "https://aihardwaresummit.com",
        "xHandle": "@KisacoResearch",
        "isFeatured": True
    },
    {
        "id": "cogx-festival-2026",
        "title": "CogX Festival Global Leadership Summit",
        "category": "AI",
        "badge": "Global Leadership",
        "startDate": "2026-10-06",
        "endDate": "2026-10-07",
        "location": "London, UK",
        "venue": "The O2 London",
        "description": "Gathering world leaders, AI innovators, and tech visionaries to address how AI, quantum technologies, and autonomous agents transform our collective future.",
        "topics": ["AI Leadership", "Quantum Computing", "Future of Work", "Global Policy", "Ethics"],
        "officialUrl": "https://www.cogxfestival.com",
        "xHandle": "@cogxfest",
        "isFeatured": False
    },
    {
        "id": "dublin-tech-summit-ai-2026",
        "title": "Dublin Tech Summit: AI & Future Track",
        "category": "AI",
        "badge": "European Tech",
        "startDate": "2026-05-27",
        "endDate": "2026-05-28",
        "location": "Dublin, Ireland",
        "venue": "RDS Dublin",
        "description": "Europe's fastest-growing tech conference, featuring keynotes from AI executives, unicorn founders, and VC investors discussing generative deployment.",
        "topics": ["European Tech", "Generative AI", "Fintech AI", "Scaleups", "VC Funding"],
        "officialUrl": "https://dublintechsummit.tech",
        "xHandle": "@DubTechSummit",
        "isFeatured": False
    },
    {
        "id": "ted-ai-2026",
        "title": "TED AI 2026",
        "category": "AI",
        "badge": "Thought Leadership",
        "startDate": "2026-10-19",
        "endDate": "2026-10-21",
        "location": "San Francisco, CA, USA",
        "venue": "Herbst Theatre",
        "description": "Curated by TED. World-renowned scientists, ethicists, and pioneers deliver provocative talks on human-machine collaboration and superintelligence governance.",
        "topics": ["TED Talks", "Superintelligence", "Human-AI Symbiosis", "Creativity", "Ethics"],
        "officialUrl": "https://ted.ai",
        "xHandle": "@TED_AI",
        "isFeatured": True
    },
    {
        "id": "scale-ai-transformx-2026",
        "title": "Scale AI TransformX 2026",
        "category": "AI",
        "badge": "Foundational AI",
        "startDate": "2026-10-13",
        "endDate": "2026-10-14",
        "location": "San Francisco, CA, USA",
        "venue": "Palace of Fine Arts",
        "description": "Scale AI's premier conference covering high-quality RLHF data curation, model benchmarking, red-teaming, and enterprise AI orchestration.",
        "topics": ["RLHF Data", "Red Teaming", "Model Evaluations", "Data Quality", "Enterprise AI"],
        "officialUrl": "https://scale.com/transformx",
        "xHandle": "@scale_AI",
        "isFeatured": False
    },
    {
        "id": "odsc-east-2026",
        "title": "ODSC East 2026 (Open Data Science Conference)",
        "category": "AI",
        "badge": "Hands-on Data Science",
        "startDate": "2026-05-05",
        "endDate": "2026-05-07",
        "location": "Boston, MA, USA",
        "venue": "Boston Hynes Convention Center",
        "description": "One of the largest hands-on training conferences for data scientists and ML practitioners, featuring tutorials on PyTorch, Hugging Face, and MLOps.",
        "topics": ["Data Science", "PyTorch", "MLOps", "Model Deployment", "Hands-on Tutorials"],
        "officialUrl": "https://odsc.com/boston/",
        "xHandle": "@odsc",
        "isFeatured": False
    },
    {
        "id": "odsc-west-2026",
        "title": "ODSC West 2026 (Open Data Science Conference)",
        "category": "AI",
        "badge": "Hands-on Data Science",
        "startDate": "2026-10-27",
        "endDate": "2026-10-29",
        "location": "San Francisco, CA, USA",
        "venue": "Hyatt Regency San Francisco",
        "description": "Over 300 hours of technical training in generative AI, synthetic data generation, agent building, and production machine learning engineering.",
        "topics": ["Hands-on ML", "Synthetic Data", "Agent Frameworks", "Production AI", "LLM Stacks"],
        "officialUrl": "https://odsc.com/california/",
        "xHandle": "@odsc",
        "isFeatured": False
    },
    {
        "id": "emtech-digital-2026",
        "title": "EmTech Digital 2026 by MIT Tech Review",
        "category": "AI",
        "badge": "Executive Insight",
        "startDate": "2026-05-12",
        "endDate": "2026-05-13",
        "location": "Cambridge, MA, USA",
        "venue": "MIT Media Lab",
        "description": "MIT Technology Review's signature AI event bringing together senior business and technology decision-makers to analyze breakthrough research and commercial deployment.",
        "topics": ["MIT Tech Review", "Breakthrough Tech", "Business ROI", "AI Governance", "Research"],
        "officialUrl": "https://event.technologyreview.com/emtech-digital-2026/",
        "xHandle": "@techreview",
        "isFeatured": True
    },
    {
        "id": "venturebeat-transform-2026",
        "title": "VentureBeat Transform 2026",
        "category": "AI",
        "badge": "Enterprise AI Strategy",
        "startDate": "2026-07-08",
        "endDate": "2026-07-10",
        "location": "San Francisco, CA, USA",
        "venue": "Warfield Theatre San Francisco",
        "description": "The leading executive event on AI and data technology, highlighting actionable insights, cybersecurity for AI, and autonomous workflow integration.",
        "topics": ["Enterprise Strategy", "AI Cybersecurity", "Agentic Automation", "Data Management", "ROI"],
        "officialUrl": "https://events.venturebeat.com/transform-2026/",
        "xHandle": "@VentureBeat",
        "isFeatured": False
    },
    {
        "id": "ai-world-congress-2026",
        "title": "AI World Congress 2026",
        "category": "AI",
        "badge": "Global Forum",
        "startDate": "2026-06-17",
        "endDate": "2026-06-18",
        "location": "London, UK",
        "venue": "Kensington Conference and Event Centre",
        "description": "International forum analyzing AI applications in smart cities, financial risk forecasting, automated healthcare, and defense robotics.",
        "topics": ["Smart Cities", "Robotics", "FinTech AI", "HealthTech", "Global Governance"],
        "officialUrl": "https://aiworldcongress.com",
        "xHandle": "@AIWorldCongress",
        "isFeatured": False
    },
    {
        "id": "deep-learning-summit-sf-2026",
        "title": "Deep Learning Summit San Francisco 2026",
        "category": "AI",
        "badge": "Deep Tech Summit",
        "startDate": "2026-04-16",
        "endDate": "2026-04-17",
        "location": "San Francisco, CA, USA",
        "venue": "Marriott Marquis San Francisco",
        "description": "Organized by RE•WORK. Bridging the gap between the latest technological research advancements and real-world business applications of deep learning.",
        "topics": ["Deep Learning", "Generative Vision", "Reinforcement Learning", "Neural Nets", "Startups"],
        "officialUrl": "https://www.re-work.co/events/deep-learning-summit-san-francisco-2026",
        "xHandle": "@reworkDL",
        "isFeatured": False
    },
    {
        "id": "ai-big-data-expo-global-2026",
        "title": "AI & Big Data Expo Global 2026",
        "category": "AI",
        "badge": "Enterprise Expo",
        "startDate": "2026-11-25",
        "endDate": "2026-11-26",
        "location": "London, UK",
        "venue": "Olympia London",
        "description": "7,000+ attendees exploring enterprise AI, machine learning, data engineering, security, and digital transformation.",
        "topics": ["Big Data", "Data Engineering", "Enterprise AI", "Cloud Infrastructure", "Security"],
        "officialUrl": "https://www.ai-expo.net/global/",
        "xHandle": "@ai_expo",
        "isFeatured": False
    },
    {
        "id": "supercomputing-sc26",
        "title": "SC26 (Supercomputing Conference)",
        "category": "AI",
        "badge": "HPC & AI Superclusters",
        "startDate": "2026-11-15",
        "endDate": "2026-11-20",
        "location": "Atlanta, GA, USA",
        "venue": "Georgia World Congress Center",
        "description": "The international conference for high performance computing, networking, storage, and analysis. Showcasing exascale computing and massive AI training superclusters.",
        "topics": ["Supercomputing", "HPC", "Exascale AI", "High Bandwidth Networks", "Data Centers"],
        "officialUrl": "https://sc26.supercomputing.org",
        "xHandle": "@Supercomputing",
        "isFeatured": False
    },
    {
        "id": "eccv-2026",
        "title": "ECCV 2026 (European Conference on Computer Vision)",
        "category": "AI",
        "badge": "Vision AI Research",
        "startDate": "2026-09-27",
        "endDate": "2026-10-02",
        "location": "Milan, Italy",
        "venue": "Allianz MiCo Milano Convention Centre",
        "description": "Europe's top biennial computer vision conference showcasing foundational vision models, spatial AI, autonomous systems, and generative image synthesis.",
        "topics": ["Computer Vision", "Generative Models", "Spatial Computing", "Neural Radiance", "Robotics"],
        "officialUrl": "https://eccv.ecva.net",
        "xHandle": "@eccvconf",
        "isFeatured": False
    },
    {
        "id": "emnlp-2026",
        "title": "EMNLP 2026 (Empirical Methods in NLP)",
        "category": "AI",
        "badge": "Top NLP Conference",
        "startDate": "2026-11-12",
        "endDate": "2026-11-16",
        "location": "Abu Dhabi, UAE",
        "venue": "ADNEC Center",
        "description": "A premier conference on empirical methods in natural language processing, presenting the latest discoveries in language model scaling laws and alignment.",
        "topics": ["NLP", "Scaling Laws", "Alignment", "Evaluation Benchmarks", "Multilingual AI"],
        "officialUrl": "https://emnlp.org",
        "xHandle": "@emnlpmeeting",
        "isFeatured": False
    },
    {
        "id": "icra-2026",
        "title": "IEEE ICRA 2026 (Robotics & Automation)",
        "category": "AI",
        "badge": "Physical AI & Robotics",
        "startDate": "2026-05-18",
        "endDate": "2026-05-22",
        "location": "London, UK",
        "venue": "ExCeL London",
        "description": "The IEEE Robotics and Automation Society's flagship conference, exploring physical AI, humanoid robotics, manipulation, and autonomous navigation.",
        "topics": ["Humanoid Robotics", "Physical AI", "Manipulation", "Autonomous Navigation", "Sensors"],
        "officialUrl": "https://www.icra2026.org",
        "xHandle": "@IEEE_RAS",
        "isFeatured": True
    },
    {
        "id": "corl-2026",
        "title": "CoRL 2026 (Conference on Robot Learning)",
        "category": "AI",
        "badge": "Robot Learning Flagship",
        "startDate": "2026-11-02",
        "endDate": "2026-11-05",
        "location": "Seoul, South Korea",
        "venue": "COEX Convention & Exhibition Center",
        "description": "Focused exclusively on the intersection of robotics and machine learning, highlighting policy learning, world models, and foundation models for embodied agents.",
        "topics": ["Robot Learning", "Embodied AI", "World Models", "Policy Optimization", "Reinforcement"],
        "officialUrl": "https://corl.org",
        "xHandle": "@corl_conf",
        "isFeatured": False
    },
    {
        "id": "generative-ai-world-2026",
        "title": "Generative AI World 2026",
        "category": "AI",
        "badge": "Commercial Generative AI",
        "startDate": "2026-09-15",
        "endDate": "2026-09-17",
        "location": "Boston, MA, USA",
        "venue": "Boston Marriott Copley Place",
        "description": "Focusing on enterprise ROI, commercial licensing of foundational weights, agentic coding tools, and synthetic dataset pipelines.",
        "topics": ["Enterprise ROI", "Generative Video", "Agentic Coding", "Model Governance", "Startups"],
        "officialUrl": "https://generativeaiworld.com",
        "xHandle": "@GenAIWorld",
        "isFeatured": False
    },
    {
        "id": "ai-in-finance-summit-2026",
        "title": "AI in Finance Summit New York 2026",
        "category": "AI",
        "badge": "Fintech AI",
        "startDate": "2026-04-23",
        "endDate": "2026-04-24",
        "location": "New York, NY, USA",
        "venue": "Convene New York",
        "description": "Exploring high-frequency trading models, automated risk assessment, fraud detection, and algorithmic compliance on Wall Street.",
        "topics": ["Fintech AI", "High Frequency Trading", "Fraud Detection", "Risk Models", "Compliance"],
        "officialUrl": "https://re-work.co",
        "xHandle": "@reworkFin",
        "isFeatured": False
    },
    {
        "id": "langchain-agents-worldwide-2026",
        "title": "LangChain Autonomous Agents Summit 2026",
        "category": "AI",
        "badge": "Agent Frameworks",
        "startDate": "2026-07-23",
        "endDate": "2026-07-24",
        "location": "San Francisco, CA, USA & Virtual",
        "venue": "Pier 27 San Francisco",
        "description": "Hosted by the LangChain and LangGraph teams, highlighting multi-agent orchestration, state machines, human-in-the-loop controls, and production reliability.",
        "topics": ["LangGraph", "Multi-Agent Systems", "State Machines", "Tool Calling", "Autonomous Workflows"],
        "officialUrl": "https://www.langchain.com",
        "xHandle": "@LangChainAI",
        "isFeatured": True
    },

    # -------------------------------------------------------------
    # 3. Crypto x AI, DeAI & Solana AI Ecosystem (20 Events)
    # -------------------------------------------------------------
    {
        "id": "deai-global-summit-2026",
        "title": "Global Decentralized AI (DeAI) Summit",
        "category": "DeAI",
        "badge": "Crypto x AI Premier",
        "startDate": "2026-05-22",
        "endDate": "2026-05-23",
        "location": "Singapore",
        "venue": "Marina Bay Sands",
        "description": "The definitive summit dedicated solely to the intersection of crypto and artificial intelligence. Covering decentralized training networks, sovereign AI agents, GPU compute marketplaces, and on-chain verification.",
        "topics": ["AI Agents", "Decentralized Compute", "Zero-Knowledge ML", "Solana DeAI", "Tokenized Intelligence"],
        "officialUrl": "https://deaisummit.io",
        "xHandle": "@DeAISummit",
        "isFeatured": True
    },
    {
        "id": "solana-ai-buildathon-2026",
        "title": "Solana AI Agent Buildathon",
        "category": "DeAI",
        "badge": "Solana DeAI Hackathon",
        "startDate": "2026-06-01",
        "endDate": "2026-06-15",
        "location": "Virtual / Global Hubs",
        "venue": "Global Discord, Luma & Hacker Houses",
        "description": "A worldwide competitive sprint for developers engineering autonomous, on-chain AI agents powered by Solana. Focus areas include micro-transactions, automated market making, and verifiable model inference.",
        "topics": ["Solana Agents", "Micro-Payments", "zkML", "Autonomous Trading", "DePIN Compute"],
        "officialUrl": "https://solana.com/developers",
        "xHandle": "@SolanaDevelopers",
        "isFeatured": True
    },
    {
        "id": "crypto-x-ai-san-francisco-2026",
        "title": "Crypto x AI Summit SF 2026",
        "category": "DeAI",
        "badge": "Silicon Valley Summit",
        "startDate": "2026-08-14",
        "endDate": "2026-08-15",
        "location": "San Francisco, CA, USA",
        "venue": "Palace of Fine Arts",
        "description": "Where Silicon Valley frontier AI researchers connect with decentralized protocol architects to build resilient, permissionless agent infrastructure and decentralized compute layers.",
        "topics": ["Agent Swarms", "DePIN GPUs", "Open-Source Models", "Crypto Rails for AI", "Zero-Knowledge ML"],
        "officialUrl": "https://lu.ma",
        "xHandle": "@DverseAI",
        "isFeatured": True
    },
    {
        "id": "superteam-global-ai-buildathon-2026",
        "title": "Superteam Global Solana AI Buildathon",
        "category": "DeAI",
        "badge": "Solana AI Grants",
        "startDate": "2026-07-15",
        "endDate": "2026-07-30",
        "location": "Global Hubs / Virtual",
        "venue": "Superteam Earn Portal & Virtual Hubs",
        "description": "A $250,000+ bounty buildathon sponsored by Solana ecosystem protocols to deploy autonomous Solana bots, DeFi portfolio rebalancing agents, and sentiment crawlers.",
        "topics": ["Solana", "AI Bounties", "Superteam", "Bots", "On-Chain Micro-Tipping"],
        "officialUrl": "https://superteam.fun",
        "xHandle": "@SuperteamEarn",
        "isFeatured": True
    },
    {
        "id": "bittensor-subnet-world-2026",
        "title": "Bittensor Subnet World 2026",
        "category": "DeAI",
        "badge": "DeAI Ecosystem",
        "startDate": "2026-09-14",
        "endDate": "2026-09-15",
        "location": "San Francisco, CA, USA",
        "venue": "Yerba Buena Center for the Arts",
        "description": "The gathering of subnets, miners, validators, and researchers in the Bittensor ($TAO) neural network, analyzing incentive mechanisms, synthetic data scoring, and distributed intelligence.",
        "topics": ["Bittensor", "TAO", "Subnets", "Distributed Intelligence", "Incentive Mechanisms"],
        "officialUrl": "https://bittensor.com",
        "xHandle": "@opentensor",
        "isFeatured": True
    },
    {
        "id": "asi-alliance-summit-2026",
        "title": "Artificial Superintelligence (ASI) Alliance Summit",
        "category": "DeAI",
        "badge": "Decentralized AGI",
        "startDate": "2026-05-02",
        "endDate": "2026-05-03",
        "location": "Dubai, UAE",
        "venue": "Atlantis The Royal Dubai",
        "description": "Hosted by SingularityNET, Fetch.ai, and Ocean Protocol. Exploring collective decentralized artificial general intelligence, sovereign neural agents, and open data marketplaces.",
        "topics": ["ASI Alliance", "Fetch.ai", "SingularityNET", "Decentralized AGI", "Autonomous Agents"],
        "officialUrl": "https://asi-alliance.ai",
        "xHandle": "@ASI_Alliance",
        "isFeatured": True
    },
    {
        "id": "depin-compute-day-austin-2026",
        "title": "Decentralized Compute & DePIN Day",
        "category": "DeAI",
        "badge": "DePIN & GPU Hardware",
        "startDate": "2026-03-24",
        "endDate": "2026-03-25",
        "location": "Austin, TX, USA",
        "venue": "Austin Convention Center",
        "description": "Connecting decentralized GPU networks, clustered rendering nodes, and distributed inference protocols with frontier AI startups hungry for elastic compute.",
        "topics": ["DePIN", "Decentralized Compute", "GPU Clustering", "Inference", "Solana DePIN"],
        "officialUrl": "https://depin.ninja",
        "xHandle": "@DePINday",
        "isFeatured": False
    },
    {
        "id": "zkml-hackathon-berlin-2026",
        "title": "zkML Hackathon Berlin (Verifiable AI)",
        "category": "DeAI",
        "badge": "Verifiable ML",
        "startDate": "2026-04-18",
        "endDate": "2026-04-20",
        "location": "Berlin, Germany",
        "venue": "Betahaus Berlin",
        "description": "A technical sprint for developers proving neural model inference using zero-knowledge circuits, ensuring verifiable and tamper-proof on-chain AI outputs.",
        "topics": ["zkML", "Zero-Knowledge", "Verifiable Inference", "Circom", "Cryptographic Proofs"],
        "officialUrl": "https://zkml.community",
        "xHandle": "@zkml_community",
        "isFeatured": False
    },
    {
        "id": "autonomous-agent-hack-nyc-2026",
        "title": "Autonomous Agent Hackathon NYC",
        "category": "DeAI",
        "badge": "Agentic Hackathon",
        "startDate": "2026-09-18",
        "endDate": "2026-09-20",
        "location": "New York, NY, USA",
        "venue": "Brooklyn Navy Yard",
        "description": "Hackers build self-custodial AI agents equipped with Solana wallets that autonomously trade, pay for API access, and collaborate across agent swarms.",
        "topics": ["Self-Custodial Agents", "Solana Wallets", "Agent Swarms", "Micro-Transactions", "Hackathon"],
        "officialUrl": "https://lu.ma",
        "xHandle": "@DverseAI",
        "isFeatured": True
    },
    {
        "id": "virtuals-protocol-summit-2026",
        "title": "Virtuals Protocol AI Agent Summit Tokyo",
        "category": "DeAI",
        "badge": "Co-owned AI Agents",
        "startDate": "2026-08-25",
        "endDate": "2026-08-26",
        "location": "Tokyo, Japan",
        "venue": "Mori Building Roppongi",
        "description": "Exploring tokenized, co-owned virtual personas and interactive gaming agents capable of generating autonomous revenue streams on decentralized rails.",
        "topics": ["Virtuals Protocol", "Co-owned Agents", "Gaming AI", "Tokenized Personas", "Web3 Social"],
        "officialUrl": "https://www.virtuals.io",
        "xHandle": "@virtuals_io",
        "isFeatured": False
    },
    {
        "id": "render-network-gpu-day-2026",
        "title": "Render Network Global GPU Day",
        "category": "DeAI",
        "badge": "Decentralized Rendering & AI",
        "startDate": "2026-07-28",
        "endDate": "2026-07-29",
        "location": "Los Angeles, CA, USA",
        "venue": "L.A. Live Event Deck",
        "description": "Showcasing decentralized node rendering on Solana, generative 3D NeRF rendering, and enterprise AI fine-tuning powered by the distributed Render Network.",
        "topics": ["Render Network", "Solana", "Decentralized GPU", "NeRF", "3D Generation"],
        "officialUrl": "https://rendernetwork.com",
        "xHandle": "@rendernetwork",
        "isFeatured": True
    },
    {
        "id": "deai-day-dubai-2026",
        "title": "DeAI Day Dubai (TOKEN2049 Week)",
        "category": "DeAI",
        "badge": "Token2049 Co-located",
        "startDate": "2026-04-28",
        "endDate": "2026-04-28",
        "location": "Dubai, UAE",
        "venue": "W Dubai The Palm",
        "description": "The premier side event during TOKEN2049 Dubai dedicated to sovereign agent deployment, decentralized data provenance, and Solana AI micro-economies.",
        "topics": ["Token2049", "Solana DeAI", "Data Provenance", "GPU Compute", "Networking"],
        "officialUrl": "https://lu.ma",
        "xHandle": "@DverseAI",
        "isFeatured": True
    },
    {
        "id": "solana-deai-accelerate-london-2026",
        "title": "Solana DeAI Accelerate London",
        "category": "DeAI",
        "badge": "Solana AI Incubator",
        "startDate": "2026-06-18",
        "endDate": "2026-06-19",
        "location": "London, UK",
        "venue": "Level39 Canary Wharf",
        "description": "Connecting early-stage decentralized AI startups building on Solana with venture capital firms, liquidity providers, and security auditors.",
        "topics": ["Solana", "AI Accelerators", "Venture Capital", "Audits", "DeAI Startups"],
        "officialUrl": "https://superteam.fun",
        "xHandle": "@SuperteamUK",
        "isFeatured": False
    },
    {
        "id": "ethglobal-autonomous-agents-paris-2026",
        "title": "ETHGlobal Autonomous Agents Paris",
        "category": "DeAI",
        "badge": "On-Chain Agents",
        "startDate": "2026-07-03",
        "endDate": "2026-07-05",
        "location": "Paris, France",
        "venue": "Station F",
        "description": "A targeted 3-day hackathon focused exclusively on smart contract-invoked autonomous agents, ERC-4337 session keys, and verifiable automated actions.",
        "topics": ["ERC-4337", "Session Keys", "Autonomous Actions", "Smart Contracts", "Hackathon"],
        "officialUrl": "https://ethglobal.com",
        "xHandle": "@ETHGlobal",
        "isFeatured": False
    },
    {
        "id": "ai-agent-swarms-miami-2026",
        "title": "AI Agent Swarms Summit Miami",
        "category": "DeAI",
        "badge": "Multi-Agent Systems",
        "startDate": "2026-11-18",
        "endDate": "2026-11-19",
        "location": "Miami, FL, USA",
        "venue": "Mana Wynwood Convention Center",
        "description": "Exploring cooperative agent swarms operating across decentralized protocols to solve complex predictive modeling, liquidation defense, and oracle validation.",
        "topics": ["Agent Swarms", "Cooperative AI", "Oracle Validation", "Liquidation Defense", "Solana"],
        "officialUrl": "https://lu.ma",
        "xHandle": "@DverseAI",
        "isFeatured": False
    },
    {
        "id": "decentralized-intelligence-forum-zurich-2026",
        "title": "Decentralized Intelligence Forum Zurich",
        "category": "DeAI",
        "badge": "Swiss Crypto Valley",
        "startDate": "2026-09-02",
        "endDate": "2026-09-03",
        "location": "Zurich, Switzerland",
        "venue": "Kongresshaus Zurich",
        "description": "Academic cryptography and AI researchers convene in Switzerland's Crypto Valley to discuss homomorphic encryption, privacy-preserving training, and decentralized governance.",
        "topics": ["Homomorphic Encryption", "Privacy Preserving ML", "Crypto Valley", "Governance", "ZK"],
        "officialUrl": "https://cryptovalley.swiss",
        "xHandle": "@CryptoValley",
        "isFeatured": False
    },
    {
        "id": "verifiable-inference-summit-seoul-2026",
        "title": "Verifiable Inference & On-Chain AI Summit Seoul",
        "category": "DeAI",
        "badge": "Verifiable AI",
        "startDate": "2026-09-28",
        "endDate": "2026-09-28",
        "location": "Seoul, South Korea",
        "venue": "Grand InterContinental Seoul Parnas",
        "description": "Co-located during KBW week. Focuses on consensus mechanisms for neural model verification, decentralized model weights storage, and anti-hallucination protocols.",
        "topics": ["KBW Week", "Model Verification", "Decentralized Storage", "Consensus", "Asia DeAI"],
        "officialUrl": "https://koreablockchainweek.com",
        "xHandle": "@kbwofficial",
        "isFeatured": False
    },
    {
        "id": "superteam-india-ai-track-2026",
        "title": "Superteam India Solana AI Track",
        "category": "DeAI",
        "badge": "Solana India",
        "startDate": "2026-08-01",
        "endDate": "2026-08-10",
        "location": "Bangalore, India",
        "venue": "WeWork Galaxy Residency Road",
        "description": "A 10-day intensive cohort for Indian engineers building specialized consumer and DeFi agents on Solana with direct grant funding.",
        "topics": ["Superteam India", "Solana", "AI Grants", "Consumer Agents", "Bangalore Tech"],
        "officialUrl": "https://superteam.fun/india",
        "xHandle": "@SuperteamIN",
        "isFeatured": True
    },
    {
        "id": "tokenized-ai-data-hk-2026",
        "title": "Tokenized AI & Data Marketplaces Expo Hong Kong",
        "category": "DeAI",
        "badge": "Data Monetization",
        "startDate": "2026-06-04",
        "endDate": "2026-06-05",
        "location": "Hong Kong",
        "venue": "AsiaWorld-Expo",
        "description": "Exploring data provenance, decentralized labeling networks, proprietary dataset tokenization, and royalty-sharing protocols for foundational model training.",
        "topics": ["Data Marketplaces", "Dataset Tokenization", "Data Provenance", "Royalties", "Hong Kong"],
        "officialUrl": "https://lu.ma",
        "xHandle": "@DverseAI",
        "isFeatured": False
    },
    {
        "id": "dverse-autonomous-ai-hackathon-2026",
        "title": "DVERSE Autonomous AI Knowledge Hackathon",
        "category": "DeAI",
        "badge": "Official DVERSE Event",
        "startDate": "2026-11-20",
        "endDate": "2026-11-27",
        "location": "Virtual / Global",
        "venue": "https://www.dverse.info",
        "description": "The official community hackathon by dataverse.ai ($DVERSE) on Solana. Developers, researchers, and creators build free, decentralized AI knowledge agents, open intelligence scrapers, and verifiable knowledge graphs.",
        "topics": ["$DVERSE", "Solana", "Free AI Knowledge", "Knowledge Graphs", "Decentralized AI"],
        "officialUrl": "https://www.dverse.info",
        "xHandle": "@DverseAI",
        "isFeatured": True
    }
]

def format_date_range(start_str: str, end_str: str) -> str:
    """Formats '2026-09-18' and '2026-09-20' into 'Sep 18 – 20, 2026'."""
    try:
        start_d = datetime.strptime(start_str, "%Y-%m-%d").date()
        end_d = datetime.strptime(end_str, "%Y-%m-%d").date()
        if start_d.month == end_d.month and start_d.year == end_d.year:
            if start_d.day == end_d.day:
                return start_d.strftime("%b %d, %Y")
            return f"{start_d.strftime('%b %d')} – {end_d.strftime('%d, %Y')}"
        return f"{start_d.strftime('%b %d')} – {end_d.strftime('%b %d, %Y')}"
    except Exception:
        return f"{start_str} to {end_str}"

def generate_google_cal_url(event: dict) -> str:
    """Generates a direct one-click Google Calendar add-event URL."""
    try:
        start_dt = event["startDate"].replace("-", "")
        end_date_obj = datetime.strptime(event["endDate"], "%Y-%m-%d").date()
        end_dt = end_date_obj.strftime("%Y%m%d")
        
        details = f"{event['description']}\n\nOfficial Website: {event['officialUrl']}\nCurated by dataverse.ai ($DVERSE)"
        venue_loc = f"{event['venue']}, {event['location']}"
        
        base_url = "https://calendar.google.com/calendar/render?action=TEMPLATE"
        params = [
            f"text={quote(event['title'])}",
            f"dates={start_dt}/{end_dt}",
            f"details={quote(details)}",
            f"location={quote(venue_loc)}",
            "sf=true",
            "output=xml"
        ]
        return f"{base_url}&{'&'.join(params)}"
    except Exception:
        return ""

def compute_status_and_days(start_str: str, end_str: str, today: date) -> tuple[str, int]:
    """Computes status label and integer days left until start."""
    try:
        start_d = datetime.strptime(start_str, "%Y-%m-%d").date()
        end_d = datetime.strptime(end_str, "%Y-%m-%d").date()
        
        if start_d <= today <= end_d:
            return "Live Now", 0
        elif today > end_d:
            return "Completed", -(today - end_d).days
        else:
            diff = (start_d - today).days
            if diff <= 7:
                return f"In {diff} Day{'s' if diff > 1 else ''}", diff
            elif diff <= 30:
                return f"In {diff} Days", diff
            else:
                return "Upcoming", diff
    except Exception:
        return "Upcoming", 999

def process_events():
    today = datetime.now(timezone.utc).date()
    processed = []
    
    # Deduplicate by ID
    seen_ids = set()
    for ev in CORE_EVENTS:
        if ev["id"] in seen_ids:
            continue
        seen_ids.add(ev["id"])
        
        status, days_left = compute_status_and_days(ev["startDate"], ev["endDate"], today)
        formatted_date = format_date_range(ev["startDate"], ev["endDate"])
        google_cal = generate_google_cal_url(ev)
        
        item = {
            **ev,
            "status": status,
            "daysLeft": days_left,
            "formattedDate": formatted_date,
            "googleCalendarUrl": google_cal
        }
        processed.append(item)
    
    # Sort chronologically by startDate
    processed.sort(key=lambda x: x["startDate"])
    
    output_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "public", "events.json")
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(processed, f, indent=2, ensure_ascii=False)
        f.write("\n")
    
    print(f"Successfully processed {len(processed)} global events -> {output_path}")

if __name__ == "__main__":
    process_events()
